{{- if and .Values.kustvaktFull.enabled (.Values.full.kustvaktLdap.enabled) }}
{{- if not .Values.full.kustvaktLdap.passwordSecret }}
{{- if .Values.full.kustvaktLdap.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "korap.fullname" . }}-kustvakt-ldap-secret
  labels:
    {{- include "korap.labels" . | nindent 4 }}
    variant: full
type: Opaque
data:
  {{ .Values.full.kustvaktLdap.passwordKey }}: {{ .Values.full.kustvaktLdap.password | b64enc }}
{{- end }}
{{- end }}
{{- end }}
