{{- if and (.Values.full | default dict).enabled ((.Values.full | default dict).superClientInfo | default dict).enabled (not (.Values.full | default dict).superClientInfoSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "korap.fullname" . }}-super-client-info
  labels:
    {{- include "korap.labels" . | nindent 4 }}
type: Opaque
data:
  super_client_info: {{ include "korap.superClientInfo" . | b64enc | quote }}
{{- end }}
